# Generated by Django 5.1.1 on 2024-10-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="education",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
